<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Metamorphosis Design Free Css Templates</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<link href="styles.css" rel="stylesheet" type="text/css" media="screen" />
<style type="text/css">
<!--
.style1 {color: #FF0000}
.style2 {color: #00CCFF}
.style3 {
	color: #CC0000;
	font-size: 10px;
}
.style4 {color: #000000}
-->
</style></head>
<body>
<div id="content">
<!-- header begins -->
<div id="header"> 
	<div id="logo">
	  <h1><center>
		  <p><span class="style2"><marquee behavior="alternate">
		  </marquee>
		  </span><span class="style2">
		  <marquee behavior="alternate" class="style1">
		  <u>CITY OF NAWABS</u>
		  </marquee>
		  </span><span class="style2">
		  <marquee behavior="alternate">
		  </marquee>
            </span> <span class="style1">
          </span></p>
		  </center></h1>
		
	</div>
</div>
  <div id="menu">
		<ul>
			<li id="button1"><a href="index.jsp"  title="">Home</a></li>
			<li id="button2"><a href="imagegallery.jsp" title="">Image Gallery</a></li>
			<li id="button3"><a href="FEEDBACKNN.jsp" title="">Feed Back</a></li>
			<li id="button4"><a href="aboutus.jsp" title="">About Us</a></li>
			<li id="button5"><a href="map.jsp" title="">City Map</a></li>
		</ul>
  </div>
	<!-- header ends -->
<!-- content begins -->

















<div id="main">
	<div id="right">
	
	
	
	
	
	
       
	   
	   <h1>GGT</h1><BR />
	   <h1>GGT</h1><BR />
	   <h1>GGT</h1><BR />
	   <h1>GGT</h1><BR /><h1>GGT</h1><BR /><h1>GGT</h1><BR /><h1>GGT</h1><BR /><h1>GGT</h1><BR />
	  
	  
	 
	  
	  
	  
	  
	  
	  
	  
	   
	   
</div>
	

	<br /><br />
      <p align="center"><img src=../images/anim/ibm.gif width="150" height="60"></p><br />
      <p align="center"><img src="../images/hotjobs/007.gif" width="120" height="115"></p>
      <p align="center">&nbsp;</p>
      <p align="center"><img src="../images/hotjobs/microsoft.gif" width="146" height="46">&nbsp;</p>      
      <p align="center">&nbsp;</p>
	
	
	
	
	
	<div id="left">
	<div id="left_top"></div>
	<div id="categories">
			<h3>Searching Categories</h3>
			<ul>
			       <li><a href="howtoreach.jsp">How To reach</a></li>      
				  <li><a href="bada.jsp">Historical places</a></li>
				  <li><a href="#">Tour and Travel</a></li>
				  <li><a href="#">Educational environment</a></li>
				  <li><a href="#">Events and shopping</a></li>
				  <li><a href="#">Medical services</a></li>
				  <li><a href="#">Hotels</a></li>
				  <li><a href="#">Food & drink</a></li>
				  <li><a href="#">Contact Us</a></li>
			</ul>
	</div>
	
	




<div style="clear:both"></div>
<!--content ends -->
<!--footer begins -->
	</div>
</div>
</div>
<div id="bot">
<div id="footer">
<p>Copyright  2010. <a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a> | <a href="http://validator.w3.org/check/referer" title="This page validates as XHTML 1.0 Transitional"><abbr title="eXtensible HyperText Markup Language">XHTML</abbr></a> | <a href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS</abbr></a></p> 
	<p>Design by <a href="http://www.metamorphozis.com/" title="Free Web Templates">Free Web Templates</a>
		</p>
	</div>
</div>
<!-- footer ends-->
</body>
</html>